# Generated by Django 5.1 on 2025-01-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_time",
            field=models.TimeField(),
        ),
    ]
